Cole lecture
jameshughes89/cs4XX-EvolutionaryComputation pull request #251
Opened 2023-11-13 17:41 UTC by CMacD12

:new:

### What

Artificial Life Lecture - Cole MacDonald

### Why

For lecture presentation

### Where

In Student lectures directory

2023-11-13 18:20 UTC, jameshughes89 requested changes
It feels like it's missing something --- perhaps add a section at the end mentioning some other things within the area of artificial life that's been done.

2023-11-14 17:28 UTC, CMacD12 commented
> It feels like it's missing something --- perhaps add a section at the end mentioning some other things within the area of artificial life that's been done.

I added in a new section and branched out

2023-11-14 17:49 UTC, jameshughes89 commented on .gitignore
revert these changes

2023-11-14 17:49 UTC, jameshughes89 commented on .buildinfo
remove this file.

2023-11-14 17:50 UTC, jameshughes89 commented on site/student-lectures/Artificial-Life/artificial_life.rst
> +.. figure:: Logical_deterministic_individual-based_cellular_automata_model_of_interspecific_competition_for_a_single_limited_resource.gif
why a dash in with the underscores in the file names?

2023-11-14 17:51 UTC, jameshughes89 commented on site/student-lectures/Artificial-Life/artificial_life.rst
> +    Logical deterministic individual-based cellular automata model of interspecific competition for a single limited resource
period at the end of the caption

2023-11-14 17:51 UTC, jameshughes89 commented on site/student-lectures/Artificial-Life/artificial_life.rst
> +    Examples of 3D creatures that evolved in Karl Sims' simulation
period.

2023-11-14 17:52 UTC, jameshughes89 requested changes
Make the final few changes and then it's good to go.

2023-11-14 18:30 UTC, jameshughes89 approved these changes

2023-11-14 18:32 UTC, merged