fixed lecture
jameshughes89/cs4XX-EvolutionaryComputation pull request #271
Opened 2023-11-21 13:51 UTC by MA-Penner

### Related Issues or PRs

if this is the right thing it should have fixed all the issues 

### What

fixed all issues and more spelling and references 
### Why

to make the lecture more polished 
### Where

all spots there were issues

2023-11-21 13:52 UTC, jameshughes89 requested changes
Just remove the vs code thing

2023-11-21 13:52 UTC, jameshughes89 commented on .vscode/settings.json
remove this

2023-11-21 23:54 UTC, MA-Penner commented
I think I changed it,, is the file gone one your side now ?

2023-11-22 15:45 UTC, jameshughes89 approved these changes

2023-11-22 15:46 UTC, merged