Finished Student Lecture Ant Colony Optimization
jameshughes89/cs4XX-EvolutionaryComputation pull request #354
Opened 2024-11-17 23:15 UTC by DippyMcSkippy

:mortar_board: 

### What

Finished Student Lecture Ant Colony Optimization

### Why

To merge with site ahead of lecture date

### Where

In the student lecture section

2024-11-17 23:21 UTC, jameshughes89 requested changes
Something is wrong. 
![image](https://github.com/user-attachments/assets/8eb30c54-18cf-4bf5-b73f-70abeba690ee)

2024-11-18 00:03 UTC, DippyMcSkippy commented on site/student-lectures/ant/ants.html
This file was refactored into Ant Colony Optimization.html

2024-11-18 00:03 UTC, DippyMcSkippy commented on site/student-lectures/ant/base backyard.jpg
This was an extra version of a an image that already existed

2024-11-18 00:03 UTC, DippyMcSkippy commented on site/index.rst
This was part of the refactorization of ant/ants into Ant Colony Optimization/Ant Colony Optimization

2024-11-18 00:04 UTC, DippyMcSkippy commented
I am not sure where else the problem could be I have built the site locally and it works fine

2024-11-18 00:04 UTC, jameshughes89 commented
You will need to fix the PR to not be rewriting the whole repo.

2024-11-18 00:16 UTC, jameshughes89 commented
> I am not sure where else the problem could be I have built the site locally and it works fine

I believe the problem is that you have build the website and saved the output to the repository, and committed those changes. 

I sent you an email with some advice.

2024-11-18 00:34 UTC, jameshughes89 commented
Still have at the .html file for the index and I believe the one for your lecture too

2024-11-18 00:37 UTC, DippyMcSkippy commented
I removed those files this time

2024-11-18 00:38 UTC, jameshughes89 approved these changes
Ideally you have your py file within the src folder with unittests too, but this is fine for the lecture this week.

2024-11-18 00:38 UTC, merged

2024-11-18 00:38 UTC, DippyMcSkippy commented
Thank You for your help